# -*- coding: utf-8 -*-
"""eradar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofdgFxdWWisGgY53-MTZ8fmXjbnYq2Y6
"""

!pip install regex beautifulsoup4 lxml tqdm xlsxwriter

#%%
from __future__ import unicode_literals
import requests
from bs4 import BeautifulSoup
import pandas as pd
import regex as re
import time
from datetime import datetime
import json
from tqdm.notebook import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
import xlsxwriter
import os

from google.colab import drive
drive.mount('/content/drive')

BASE_URL = "https://e-radar.online"
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
MAX_WORKERS = 5
SAVE_PATH = '/content/drive/MyDrive/data/'
os.makedirs(SAVE_PATH, exist_ok=True)

# Wszystkie kategorie z dropdown "Teksty"
CATEGORIES = [
    "dramat", "esej", "krytyka", "od%2Credakcji", "ogloszenie",
    "poezja", "proza", "recenzje", "reportaz", "rozmowa", "scenariusz"
]

# === TEST MODE ===
TEST_MODE = False

#%%
def get_category_links(category_slug, page_num=1):
    """Pobiera linki do artykułów z jednej strony kategorii"""
    url = f"{BASE_URL}/pl/magazyn/{category_slug}.html"
    if page_num > 1:
        url += f"?page={page_num}"
    try:
        r = requests.get(url, headers=HEADERS, timeout=30)
        r.encoding = 'utf-8'
        if r.status_code != 200:
            return [], 1
        soup = BeautifulSoup(r.text, 'lxml')

        # Linki do artykułów - szukamy linków "więcej/більше/Mehr"
        links = []
        for a in soup.find_all('a', href=True):
            href = a['href']
            if '/pl/magazyn/' in href and href.count('/') >= 4 and href not in links:
                if href.startswith('/'):
                    href = f"{BASE_URL}{href}"
                if href.startswith(BASE_URL) and href not in links:
                    links.append(href)

        # Deduplikacja
        links = list(dict.fromkeys(links))

        # Paginacja
        pages = []
        for a in soup.select('ul.pagination li a, li a'):
            try:
                pages.append(int(a.text.strip()))
            except ValueError:
                pass
        total_pages = max(pages) if pages else 1

        return links, total_pages
    except Exception as e:
        print(f"  Błąd {category_slug} strona {page_num}: {e}")
        return [], 1


def dictionary_of_article(article_link):
    """Scrapuje pojedynczy artykuł — zwraca dict"""
    try:
        r = requests.get(article_link, headers=HEADERS, timeout=30)
        r.encoding = 'utf-8'
        if r.status_code != 200:
            print(f"  [{r.status_code}] {article_link}")
            return None
        soup = BeautifulSoup(r.text, 'lxml')

        # Kategoria - z linka [[esej]] na górze
        kategoria = ""
        try:
            cat_links = soup.find_all('a', href=re.compile(r'/pl/magazyn/\w+\.html'))
            for cl in cat_links:
                text = cl.text.strip().strip('[]')
                if text and text.lower() in ['dramat', 'esej', 'krytyka', 'od redakcji',
                    'ogłoszenie', 'poezja', 'proza', 'recenzje', 'reportaż', 'rozmowa', 'scenariusz']:
                    kategoria = text
                    break
        except:
            pass

        # Tytuł - szukamy głównego nagłówka artykułu
        title_of_article = ""
        try:
            # Tytuł jest w tagu <title> jako "Radar - TYTUŁ"
            title_tag = soup.find('title')
            if title_tag:
                title_text = title_tag.text.strip()
                if ' - ' in title_text:
                    title_of_article = title_text.split(' - ', 1)[1].strip()
                else:
                    title_of_article = title_text
        except:
            pass

        # Tekst artykułu - główna treść (div.article-content lub podobny)
        article = ""
        try:
            # Szukamy głównego kontenera z tekstem artykułu
            # Na tej stronie tekst jest w sekcji po menu a przed footerem
            # Próbujemy różne selektory
            content = None
            for selector in ['div.article-content', 'div.content-text', 'div.post-content',
                           'article', 'div.article-body']:
                content = soup.select_one(selector)
                if content:
                    break

            if not content:
                # Fallback: szukamy największego bloku tekstu
                # Weźmy wszystkie <p> i <h2> poza nawigacją i footerem
                main_ps = []
                # Usuńmy nawigację i footer
                for nav in soup.find_all(['nav', 'header', 'footer']):
                    nav.decompose()
                for menu in soup.select('.navbar, .dropdown-menu, .footer, .partners'):
                    menu.decompose()

                # Zbieramy tekst z paragrafów
                for p in soup.find_all(['p', 'h2']):
                    text = p.get_text(strip=True)
                    # Pomijamy krótkie i nawigacyjne
                    if len(text) > 30 and 'WYDAWCA' not in text and 'FINANSOWANIE' not in text:
                        main_ps.append(p.get_text(separator=' ', strip=True))

                article = ' '.join(main_ps)
            else:
                article = content.get_text(separator=' ', strip=True)

            article = re.sub(r'\s+', ' ', article).replace('\xa0', ' ').strip()
        except:
            pass

        # Autor - na dole artykułu w sekcji [autor]
        author = ""
        try:
            # Szukamy linku do autora /pl/autorzy/
            author_links = soup.find_all('a', href=re.compile(r'/pl/autorzy/'))
            if author_links:
                author = author_links[0].text.strip()
        except:
            pass

        # Biogram autora
        biogram = ""
        try:
            # Sekcja z [autor] na dole
            for h4 in soup.find_all('h4'):
                a_tag = h4.find('a', href=re.compile(r'/pl/autorzy/'))
                if a_tag and '[autor]' in h4.text:
                    # Następny element to biogram
                    parent = h4.find_parent()
                    if parent:
                        ps = parent.find_all('p')
                        if ps:
                            biogram = ps[0].get_text(separator=' ', strip=True) if ps else ""
        except:
            pass

        # Numer wydania - z URL (np. "14-2025")
        numer = ""
        try:
            match = re.search(r'/pl/magazyn/(\d+-\d{4})/', article_link)
            if match:
                numer = match.group(1)
        except:
            pass

        # Zdjęcie główne
        photos_links = None
        try:
            img = soup.find('img', src=re.compile(r'att\.e-radar\.online.*700x500'))
            if img and img.get('src'):
                photos_links = img['src']
        except:
            pass

        return {
            "Link": article_link,
            "Data publikacji": "",  # strona nie pokazuje dat przy artykułach
            "Numer": numer,
            "Tytuł artykułu": title_of_article.replace('\xa0', ' '),
            "Tekst artykułu": article,
            "Autor": author,
            "Tagi": kategoria,
            "Linki zewnętrzne": None,
            "Zdjęcia/Grafika": True if photos_links else False,
            "Linki do zdjęć": photos_links
        }
    except Exception as e:
        print(f"  WYJĄTEK: {article_link} - {e}")
        return None


#%% KROK 1: Test połączenia
print("=== TEST połączenia ===")
r = requests.get(f"{BASE_URL}/pl/magazyn/esej.html", headers=HEADERS, timeout=30)
r.encoding = 'utf-8'
print(f"Status: {r.status_code}, Długość: {len(r.text)}")
if r.status_code == 200:
    print("✅ OK")
else:
    print("❌ Problem")

#%% KROK 2: Zbierz linki ze wszystkich kategorii
print("\n=== Pobieram linki z kategorii ===")
articles_links = []

for cat_slug in CATEGORIES:
    cat_name = cat_slug.replace('%2C', ',')
    links_p1, total_pages = get_category_links(cat_slug, 1)
    print(f"{cat_name}: {len(links_p1)} artykułów, {total_pages} stron")
    articles_links.extend(links_p1)

    for page_num in range(2, total_pages + 1):
        links_pn, _ = get_category_links(cat_slug, page_num)
        articles_links.extend(links_pn)
        time.sleep(0.3)

# Tylko polskie teksty (/pl/)
articles_links = [l for l in articles_links if '/pl/magazyn/' in l]
articles_links = list(dict.fromkeys(articles_links))  # deduplikacja zachowująca kolejność

if TEST_MODE:
    articles_links = articles_links[:10]

print(f"\nLinki do pobrania: {len(articles_links)}")
for link in articles_links[:5]:
    print(f"  {link}")

#%% KROK 3: Scrapuj artykuły
print(f"\n=== Scrapuję {len(articles_links)} artykułów ===")
all_results = []
errors = []

if TEST_MODE:
    for i, link in enumerate(articles_links):
        print(f"[{i+1}/{len(articles_links)}] {link}")
        result = dictionary_of_article(link)
        if result:
            all_results.append(result)
            print(f"  ✅ '{result['Tytuł artykułu'][:60]}' | {result['Autor']} | [{result['Tagi']}]")
        else:
            errors.append(link)
            print(f"  ❌ błąd")
        time.sleep(0.5)
else:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(dictionary_of_article, link): link for link in articles_links}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Artykuły"):
            result = future.result()
            if result is not None:
                all_results.append(result)
            else:
                errors.append(futures[future])

print(f"\n=== WYNIK: {len(all_results)}/{len(articles_links)} ===")

#%% KROK 4: Podgląd
if all_results:
    df = pd.DataFrame(all_results)
    df = df.sort_values('Numer', ascending=False)
    print(df[["Numer", "Tytuł artykułu", "Autor", "Tagi"]].to_string())
else:
    print("Brak wyników!")

#%% KROK 5: Zapis (odkomentuj po teście + TEST_MODE = False)
today = datetime.today().date()

with open(f'{SAVE_PATH}e-radar_{today}.json', 'w', encoding='utf-8') as f:
    json.dump(all_results, f, ensure_ascii=False, default=str)

with pd.ExcelWriter(
    f"{SAVE_PATH}e-radar_{today}.xlsx",
    engine='xlsxwriter',
    engine_kwargs={'options': {'strings_to_urls': False}}
) as writer:
    df.to_excel(writer, 'Posts', index=False)

if errors:
    with open(f'{SAVE_PATH}e-radar_errors_{today}.json', 'w', encoding='utf-8') as f:
        json.dump(errors, f, ensure_ascii=False, default=str)

print(f"Zapisano do {SAVE_PATH}e-radar_{today}.json i .xlsx")
print(f"Artykułów: {len(all_results)}, Błędów: {len(errors)}")