# -*- coding: utf-8 -*-
"""michalzdunik

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egdDYQq9AFWvSzekz8xRgScO2CoeFjPx
"""

import json
import os
import csv
from bs4 import BeautifulSoup
from datetime import datetime


with open('/content/michalzdunikjson.json', 'r', encoding='utf8') as file:
    json_data = json.load(file)


fieldnames = ["Link", "Data publikacji", "Tytuł artykułu", "Tekst artykułu", "Autor", "Tagi", "Linki zewnętrzne", "Zdjęcia/Grafika", "Filmy", "Linki do zdjęć"]


def remove_html_tags(text):
    soup = BeautifulSoup(text, 'html.parser')
    return soup.get_text()

def process_article(article):
    article_link = article['link']
    date_of_publication = article['date']
    # Konwersja daty na format YYYY-MM-DD
    date_of_publication = datetime.strptime(date_of_publication, "%Y-%m-%dT%H:%M:%S").strftime("%Y-%m-%d")
    title_of_article = article['title']['rendered']
    article_content = remove_html_tags(article['content']['rendered'])
    author = "Michał Zdunik"
    tags = article.get('tags', [])

    soup = BeautifulSoup(article['content']['rendered'], 'html.parser')
    external_links = [a['href'] for a in soup.find_all('a', href=True)]

    photos_links = [img['src'] for img in soup.find_all('img', src=True)]
    has_graphics = bool(photos_links)
    has_videos = bool(soup.find_all('iframe'))

    return {
        "Link": article_link,
        "Data publikacji": date_of_publication,
        "Tytuł artykułu": title_of_article.replace('\xa0', ' ').replace('\n', ' '),
        "Tekst artykułu": article_content.replace('\xa0', ' ').replace('\n', ' '),
        "Autor": author,
        "Tagi": tags,
        "Linki zewnętrzne": external_links,
        "Zdjęcia/Grafika": has_graphics,
        "Filmy": has_videos,
        "Linki do zdjęć": photos_links
    }


all_articles = [process_article(article) for article in json_data]

output_csv_file = 'michalzdunik_2024-06-14.csv'
with open(output_csv_file, 'w', encoding='utf8', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for article in all_articles:
        writer.writerow(article)


output_json_file = 'michalzdunik_2024-06-14.json'
with open(output_json_file, 'w', encoding='utf8') as jsonfile:
    json.dump(all_articles, jsonfile, ensure_ascii=False, indent=4)

print(f"Dane zostały zapisane do plików {output_csv_file} i {output_json_file}")

len(all_articles)