# -*- coding: utf-8 -*-
"""terazteatr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13JcnbdLvU4cgDM_ZXDz1TeXVjZaUxzeB
"""

!pip install regex beautifulsoup4 lxml tqdm xlsxwriter

#%%
from __future__ import unicode_literals
import requests
from bs4 import BeautifulSoup
import pandas as pd
import regex as re
import time
import copy
from datetime import datetime
import json
from tqdm.notebook import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
import xlsxwriter
import os
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from google.colab import drive
drive.mount('/content/drive')

BASE_URL = "https://www.terazteatr.pl"
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
MAX_WORKERS = 5
TOTAL_PAGES = 813  # ostatnia strona archiwum
SAVE_PATH = '/content/drive/MyDrive/data/'
os.makedirs(SAVE_PATH, exist_ok=True)

# === TEST MODE: zmień na False żeby pobrać wszystko ===
TEST_MODE = False

#%%
def date_change_format(date_str):
    """'23 września 2013' -> '2013-09-23'"""
    date_str = date_str.strip()
    lookup_table = {
        "stycznia": "01", "lutego": "02", "marca": "03",
        "kwietnia": "04", "maja": "05", "czerwca": "06",
        "lipca": "07", "sierpnia": "08", "września": "09",
        "października": "10", "listopada": "11", "grudnia": "12"
    }
    for name, num in lookup_table.items():
        if name in date_str.lower():
            date_str_clean = date_str.lower().replace(name, num).strip()
            # usuń "r." na końcu jeśli jest
            date_str_clean = re.sub(r'\s*r\.?\s*$', '', date_str_clean).strip()
            parts = date_str_clean.split()
            if len(parts) == 3:
                return f"{parts[2]}-{parts[1]}-{int(parts[0]):02d}"
    return date_str


def get_archive_links(page_num):
    """Pobiera linki do artykułów z jednej strony listingu"""
    url = f"{BASE_URL}/aktualnosci,{page_num}"
    try:
        r = requests.get(url, headers=HEADERS, timeout=30, verify=False)
        r.encoding = 'utf-8'
        if r.status_code != 200:
            print(f"  Strona {page_num}: status {r.status_code}")
            return []
        soup = BeautifulSoup(r.text, 'lxml')
        links = []
        for item in soup.select('ul.news_items_full li.news_item'):
            a_tag = item.select_one('h4.title a')
            if a_tag and a_tag.get('href'):
                href = a_tag['href']
                full_link = f"{BASE_URL}{href}" if href.startswith('/') else href
                links.append(full_link)
        return links
    except Exception as e:
        print(f"  Błąd strona {page_num}: {e}")
        return []


def dictionary_of_article(article_link):
    """Scrapuje pojedynczy artykuł — zwraca dict"""
    try:
        r = requests.get(article_link, headers=HEADERS, timeout=30, verify=False)
        r.encoding = 'utf-8'
        retries = 0
        while r.status_code == 429 and retries < 5:
            time.sleep(5)
            r = requests.get(article_link, headers=HEADERS, timeout=30, verify=False)
            r.encoding = 'utf-8'
            retries += 1
        if r.status_code != 200:
            print(f"  [{r.status_code}] {article_link}")
            return None
        soup = BeautifulSoup(r.text, 'lxml')

        # Tytuł
        try:
            title_tag = soup.select_one('h2.title')
            title_of_article = title_tag.text.strip() if title_tag else ""
        except:
            title_of_article = ""

        # Data i autor z "h5.post_info" -> "23 września 2013  /  redakcja"
        date_of_publication = ""
        author = ""
        try:
            info_tag = soup.select_one('h5.post_info')
            if info_tag:
                info_text = info_tag.text.strip()
                parts = [p.strip() for p in info_text.split('/')]
                if len(parts) >= 1:
                    date_of_publication = date_change_format(parts[0].strip())
                if len(parts) >= 2:
                    author = parts[1].strip()
        except:
            pass

        # Tekst artykułu
        try:
            text_div = soup.select_one('div.text')
            if text_div:
                article = text_div.get_text(separator=' ', strip=True)
                article = re.sub(r'\s+', ' ', article).replace('\xa0', ' ')
            else:
                article = ""
        except:
            article = ""

        # Tagi
        try:
            tags_list = soup.select('ul.tags_list li a')
            tags = '|'.join([t.text.strip() for t in tags_list]) if tags_list else ""
        except:
            tags = ""

        # Źródła (linki w sekcji "źródła")
        try:
            source_links = []
            for header in soup.select('header.box_header h5'):
                if 'źródła' in header.text.lower():
                    box = header.find_parent('div', class_='box_main')
                    if box:
                        for a in box.select('div.box_content a'):
                            if a.get('href'):
                                source_links.append(a['href'])
            external_links = ' | '.join(source_links) if source_links else None
        except:
            external_links = None

        # Zdjęcie
        try:
            photo_div = soup.select_one('div.content_photo img')
            if photo_div and photo_div.get('src'):
                photos_links = photo_div['src']
            else:
                photos_links = None
        except:
            photos_links = None

        return {
            "Link": article_link,
            "Data publikacji": date_of_publication,
            "Tytuł artykułu": title_of_article.replace('\xa0', ' '),
            "Tekst artykułu": article,
            "Autor": author,
            "Tagi": tags,
            "Linki zewnętrzne": external_links,
            "Zdjęcia/Grafika": True if photos_links else False,
            "Linki do zdjęć": photos_links
        }
    except Exception as e:
        print(f"  WYJĄTEK: {article_link} - {e}")
        return None


#%% KROK 1: Test połączenia
print("=== TEST połączenia ===")
r = requests.get(f"{BASE_URL}/aktualnosci,1", headers=HEADERS, timeout=30, verify=False)
r.encoding = 'utf-8'
print(f"Status: {r.status_code}, Długość: {len(r.text)}")
if r.status_code != 200 or 'Just a moment' in r.text:
    print("❌ Strona blokuje requesty!")
else:
    print("✅ Połączenie OK")

#%% KROK 2: Pobierz linki
if TEST_MODE:
    print("\n=== TEST MODE: pobieram linki z 1. strony ===")
    articles_links = get_archive_links(1)
    articles_links = articles_links[:10]
else:
    print(f"\n=== Pobieram linki ze wszystkich {TOTAL_PAGES} stron ===")
    articles_links = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        results = list(tqdm(
            executor.map(get_archive_links, range(1, TOTAL_PAGES + 1)),
            total=TOTAL_PAGES,
            desc="Strony archiwum"
        ))
    articles_links = [link for sublist in results for link in sublist]
    articles_links = list(set(articles_links))

print(f"Linki ({len(articles_links)}):")
for link in articles_links[:10]:
    print(f"  {link}")

#%% KROK 3: Scrapuj artykuły
print(f"\n=== Scrapuję {len(articles_links)} artykułów ===")
all_results = []
errors = []

if TEST_MODE:
    # Sekwencyjnie dla debugowania
    for i, link in enumerate(articles_links):
        print(f"[{i+1}/{len(articles_links)}] {link}")
        result = dictionary_of_article(link)
        if result:
            all_results.append(result)
            print(f"  ✅ '{result['Tytuł artykułu'][:60]}' | {result['Data publikacji']} | {result['Autor']}")
        else:
            errors.append(link)
            print(f"  ❌ błąd")
        time.sleep(0.5)
else:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(dictionary_of_article, link): link for link in articles_links}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Artykuły"):
            result = future.result()
            if result is not None:
                all_results.append(result)
            else:
                errors.append(futures[future])

print(f"\n=== WYNIK: {len(all_results)}/{len(articles_links)} ===")

#%% KROK 4: Podgląd
if all_results:
    df = pd.DataFrame(all_results)
    df["Data publikacji"] = pd.to_datetime(df["Data publikacji"], errors='coerce').dt.date
    df = df.sort_values('Data publikacji', ascending=False)
    print(df[["Data publikacji", "Tytuł artykułu", "Autor"]].to_string())
else:
    print("Brak wyników!")

#%% KROK 5: Zapis (odkomentuj po udanym teście)
#%% KROK 5: Zapis
today = datetime.today().date()

with open(f'{SAVE_PATH}terazteatr_{today}.json', 'w', encoding='utf-8') as f:
    json.dump(all_results, f, ensure_ascii=False, default=str)

with pd.ExcelWriter(
    f"{SAVE_PATH}terazteatr_{today}.xlsx",
    engine='xlsxwriter',
    engine_kwargs={'options': {'strings_to_urls': False}}
) as writer:
    df.to_excel(writer, 'Posts', index=False)

if errors:
    with open(f'{SAVE_PATH}terazteatr_errors_{today}.json', 'w', encoding='utf-8') as f:
        json.dump(errors, f, ensure_ascii=False, default=str)

print(f"Zapisano do {SAVE_PATH}terazteatr_{today}.json i .xlsx")
print(f"Artykułów: {len(all_results)}, Błędów: {len(errors)}")