# -*- coding: utf-8 -*-
"""wydawnictwoproby

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164-EQnDF5AQSj2rpM81d7jwOnnGNrbme
"""

!pip install regex beautifulsoup4 lxml tqdm xlsxwriter

#%%
from __future__ import unicode_literals
import requests
from bs4 import BeautifulSoup
import pandas as pd
import regex as re
import time
from datetime import datetime
import json
from tqdm.notebook import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
import xlsxwriter
import os

from google.colab import drive
drive.mount('/content/drive')

BASE_URL = "https://wydawnictwoproby.pl"
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
MAX_WORKERS = 5
TOTAL_PAGES = 104
SAVE_PATH = '/content/drive/MyDrive/data/'
os.makedirs(SAVE_PATH, exist_ok=True)

# === TEST MODE ===
TEST_MODE = False

#%%
def get_listing_links(page_num):
    """Pobiera linki do postów z jednej strony listingu"""
    if page_num == 1:
        url = f"{BASE_URL}/category/ksiega-przyjaciol/"
    else:
        url = f"{BASE_URL}/category/ksiega-przyjaciol/page/{page_num}/"
    try:
        r = requests.get(url, headers=HEADERS, timeout=30)
        r.encoding = 'utf-8'
        if r.status_code != 200:
            return []
        soup = BeautifulSoup(r.text, 'lxml')
        links = []
        for a in soup.select('div.padding-cat-inner a.h2'):
            href = a.get('href', '')
            if href and href.startswith('http'):
                links.append(href)
        return links
    except Exception as e:
        print(f"  Błąd strona {page_num}: {e}")
        return []


def dictionary_of_article(article_link):
    """Scrapuje pojedynczy post"""
    try:
        r = requests.get(article_link, headers=HEADERS, timeout=30)
        r.encoding = 'utf-8'
        if r.status_code != 200:
            print(f"  [{r.status_code}] {article_link}")
            return None
        soup = BeautifulSoup(r.text, 'lxml')

        # Tytuł
        try:
            h1 = soup.select_one('section#single-post h1')
            title_of_article = h1.text.strip() if h1 else ""
        except:
            title_of_article = ""

        # Data - "20 04 2026"
        date_of_publication = ""
        try:
            date_span = soup.select_one('span.post-date')
            if date_span:
                raw = date_span.text.strip()  # "20 04 2026"
                parts = raw.split()
                if len(parts) == 3:
                    date_of_publication = f"{parts[2]}-{parts[1]}-{parts[0]}"
        except:
            pass

        # Autor
        author = ""
        try:
            author_div = soup.select_one('section#single-post div.h4')
            if author_div:
                author = author_div.text.strip()
        except:
            pass

        # Tekst artykułu
        article = ""
        try:
            text_div = soup.select_one('section#single-post div.mb-4')
            if text_div:
                article = text_div.get_text(separator='\n', strip=True)
                article = re.sub(r'\n{3,}', '\n\n', article).replace('\xa0', ' ').strip()
        except:
            pass

        # Zdjęcia
        photos_links = None
        try:
            text_div = soup.select_one('section#single-post div.mb-4')
            if text_div:
                imgs = text_div.find_all('img')
                photo_urls = [img['src'] for img in imgs if img.get('src') and 'wp-content/uploads' in img['src']]
                photos_links = ' | '.join(photo_urls) if photo_urls else None
        except:
            pass

        # Zdjęcie profilowe autora
        author_photo = None
        try:
            author_img = soup.select_one('section#single-post div.cat-group img.rounded-circle')
            if author_img and author_img.get('src'):
                author_photo = author_img['src']
        except:
            pass

        return {
            "Link": article_link,
            "Data publikacji": date_of_publication,
            "Tytuł artykułu": title_of_article,
            "Tekst artykułu": article,
            "Autor": author,
            "Tagi": "Księga Przyjaciół",
            "Linki zewnętrzne": None,
            "Zdjęcia/Grafika": True if photos_links else False,
            "Linki do zdjęć": photos_links
        }
    except Exception as e:
        print(f"  WYJĄTEK: {article_link} - {e}")
        return None

#%% KROK 1: Test
print("=== TEST połączenia ===")
r = requests.get(f"{BASE_URL}/category/ksiega-przyjaciol/", headers=HEADERS, timeout=30)
r.encoding = 'utf-8'
print(f"Status: {r.status_code}, Długość: {len(r.text)}")

#%% KROK 2: Pobierz linki
print(f"\n=== Pobieram linki ===")
if TEST_MODE:
    articles_links = get_listing_links(1)[:10]
else:
    articles_links = []
    for page_num in tqdm(range(1, TOTAL_PAGES + 1), desc="Strony"):
        links = get_listing_links(page_num)
        articles_links.extend(links)
        time.sleep(0.3)
    articles_links = list(dict.fromkeys(articles_links))

print(f"Linki: {len(articles_links)}")
for link in articles_links[:5]:
    print(f"  {link}")

#%% KROK 3: Scrapuj
print(f"\n=== Scrapuję {len(articles_links)} artykułów ===")
all_results = []
errors = []

if TEST_MODE:
    for i, link in enumerate(articles_links):
        print(f"[{i+1}/{len(articles_links)}] {link}")
        result = dictionary_of_article(link)
        if result:
            all_results.append(result)
            print(f"  ✅ '{result['Tytuł artykułu'][:50]}' | {result['Data publikacji']} | {result['Autor']}")
        else:
            errors.append(link)
            print(f"  ❌")
        time.sleep(0.5)
else:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(dictionary_of_article, link): link for link in articles_links}
        for future in tqdm(as_completed(futures), total=len(futures), desc="Artykuły"):
            result = future.result()
            if result is not None:
                all_results.append(result)
            else:
                errors.append(futures[future])

print(f"\n=== WYNIK: {len(all_results)}/{len(articles_links)} ===")

#%% KROK 4: Podgląd
if all_results:
    df = pd.DataFrame(all_results)
    df["Data publikacji"] = pd.to_datetime(df["Data publikacji"], errors='coerce').dt.date
    df = df.sort_values('Data publikacji', ascending=False)
    print(df[["Data publikacji", "Tytuł artykułu", "Autor"]].to_string())
    print(f"\n--- Fragment tekstu ---")
    print(all_results[0]['Tekst artykułu'][:300])
else:
    print("Brak wyników!")

#%% KROK 5: Zapis (odkomentuj + TEST_MODE = False)
today = datetime.today().date()
with open(f'{SAVE_PATH}wydawnictwoproby_{today}.json', 'w', encoding='utf-8') as f:
    json.dump(all_results, f, ensure_ascii=False, default=str)
with pd.ExcelWriter(
    f"{SAVE_PATH}wydawnictwoproby_{today}.xlsx",
    engine='xlsxwriter',
    engine_kwargs={'options': {'strings_to_urls': False}}
) as writer:
    df.to_excel(writer, 'Posts', index=False)
if errors:
    with open(f'{SAVE_PATH}wydawnictwoproby_errors_{today}.json', 'w', encoding='utf-8') as f:
        json.dump(errors, f, ensure_ascii=False, default=str)
print(f"Zapisano do {SAVE_PATH}wydawnictwoproby_{today}.json i .xlsx")